services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 041124
      MYSQL_DATABASE: myccontadores
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nextcloud_backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p041124"]
      interval: 10s
      timeout: 5s
      retries: 5

  springboot-app:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/myccontadores
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 041124
    networks:
      - nextcloud_backend

volumes:
  mysql_data:

networks:
  nextcloud_backend:
    external: false